### ISSUE TITLE
Get a working .ini file for 150-isotope network.

### ISSUE THREAD

**Issue by BenBrock** [jayjaybillings/fern#1]
This .ini file for 150-isotope network results in a segmentation violation.  Pls, Jay?  How to .ini?

```
[network]
numSpecies = 150
numReactions = 1604
numReactionGroups = 742
massTol = 1.0e-7
fluxFrac = 0.01
networkFile = ../fern/data/CUDAnet_150.inp
rateFile = ../fern/data/rateLibrary_150.data

[initialConditions]
T9 = 7.0;
startTime = 1.0e-20;
endTime = 1.0e-3;
initialTimeStep = 1.23456789e-22;
density = 1.0e8;
```

**Comment by jayjaybillings** [comment]
Interesting bug. It is dying when it is trying to load the fluxes, but the debugger says all the values are OK. I'll look into it.

**Comment by jayjaybillings** [comment]
Oh hell. Yeah, this will take a bit. I'll have to work on this one for a bit.

It is a problem with the dynamic memory and sitting right on top of that DFoC bug in Network.cpp.

**Comment by jayjaybillings** [comment]
valgrind: the 'impossible' happened:
   Killed by fatal signal
