### ISSUE TITLE
Add more flags to be used in CMakeList.

### ISSUE THREAD

**Issue by BenBrock** [jayjaybillings/fern#2]
Deal intelligently with using compiler flags.  Good ones to have are -O and -g.  Another one of my favorites is -Wall.  We should have a way to deal with flags well.

**Comment by jayjaybillings** [comment]
CMake deals with these flags very intelligently. All you need to do for your desired set of flags is to configure with

CXX_FLAGS="-O3 -g -Wall" cmake ../

and that will change the flags. You can also switch between debug and release mode by changing that in the configuration script in the readme. If you have a specific example, please describe it and I will show you an actual command.

**Comment by jayjaybillings** [comment]
There was a problem with this for which I just pushed the fix. Also, don't use double quotes. Just do

CXX_FLAGS="-Wall" cmake ../ -DCMAKE_BUILD_TYPE=RelWithDebugInfo

Closing this as fixed.
