### ISSUE TITLE
"Call to 'abs' is abmiguous" when making FERN

### ISSUE THREAD

**Issue by danshyles** [jayjaybillings/fern#3]
I'm trying to make FERN after using cmake, but I'm getting this error. I've bolded what is of concern in this issue. Jay suggests that it is due to std::abs() expecting integers when they are being passed doubles. Any thoughts on how to resolve this?

[  5%] Building CXX object src/CMakeFiles/fern.dir/Globals.cpp.o
[ 10%] Building CXX object src/CMakeFiles/fern.dir/IntegrationData.cpp.o
[ 15%] Building CXX object src/CMakeFiles/fern.dir/JavaComparisonTest.cpp.o
In file included from /Users/Dan/Desktop/Research/FERN/fernRefactor/fern/src/JavaComparisonTest.cpp:40:
/Users/Dan/Desktop/Research/FERN/fernRefactor/fern/tpls/fire/parsers/BasicDelimitedTextParser.h:146:26: warning: logical not is only applied to the left hand side of this comparison
      [-Wlogical-not-parentheses]
                                if (!line.empty() && !line.find("#") == 0) {
                                                     ^               ~~
/Users/Dan/Desktop/Research/FERN/fernRefactor/fern/tpls/fire/parsers/BasicDelimitedTextParser.h:146:26: note: add parentheses after the '!' to evaluate the comparison first
                                if (!line.empty() && !line.find("#") == 0) {
                                                     ^
                                                      (                  )
/Users/Dan/Desktop/Research/FERN/fernRefactor/fern/tpls/fire/parsers/BasicDelimitedTextParser.h:146:26: note: add parentheses around left hand side expression to silence this warning
                                if (!line.empty() && !line.find("#") == 0) {
                                                     ^
                                                     (              )
/Users/Dan/Desktop/Research/FERN/fernRefactor/fern/tpls/fire/parsers/BasicDelimitedTextParser.h:146:26: warning: logical not is only applied to the left hand side of this comparison
      [-Wlogical-not-parentheses]
                                if (!line.empty() && !line.find("#") == 0) {
                                                     ^               ~~
/Users/Dan/Desktop/Research/FERN/fernRefactor/fern/src/JavaComparisonTest.cpp:130:9: note: in instantiation of member function 'fire::BasicDelimitedTextParser<double>::parse' requested here
        parser.parse();
               ^
/Users/Dan/Desktop/Research/FERN/fernRefactor/fern/tpls/fire/parsers/BasicDelimitedTextParser.h:146:26: note: add parentheses after the '!' to evaluate the comparison first
                                if (!line.empty() && !line.find("#") == 0) {
                                                     ^
                                                      (                  )
/Users/Dan/Desktop/Research/FERN/fernRefactor/fern/tpls/fire/parsers/BasicDelimitedTextParser.h:146:26: note: add parentheses around left hand side expression to silence this warning
                                if (!line.empty() && !line.find("#") == 0) {
                                                     ^
                                                     (              )
2 warnings generated.
[ 21%] Building CXX object src/CMakeFiles/fern.dir/kernels.cpp.o
[ 26%] Building CXX object src/CMakeFiles/fern.dir/main.cpp.o
**In file included from /Users/Dan/Desktop/Research/FERN/fernRefactor/fern/src/main.cpp:39:
/Users/Dan/Desktop/Research/FERN/fernRefactor/fern/src/DefaultStepper.h:143:28: error: call to 'abs' is ambiguous
                        fern_real massChecker = std::abs(sumXLast - sumX);
                                                ^~~~~~~~
/usr/include/stdlib.h:129:6: note: candidate function
int      abs(int) __pure2;
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:159:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:161:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                           ^
In file included from /Users/Dan/Desktop/Research/FERN/fernRefactor/fern/src/main.cpp:39:
/Users/Dan/Desktop/Research/FERN/fernRefactor/fern/src/DefaultStepper.h:145:8: error: call to 'abs' is ambiguous
                        if (std::abs(test2) > std::abs(test1) && massChecker > network.massTol) {
                            ^~~~~~~~
/usr/include/stdlib.h:129:6: note: candidate function
int      abs(int) __pure2;
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:159:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:161:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                           ^
In file included from /Users/Dan/Desktop/Research/FERN/fernRefactor/fern/src/main.cpp:39:
/Users/Dan/Desktop/Research/FERN/fernRefactor/fern/src/DefaultStepper.h:145:26: error: call to 'abs' is ambiguous
                        if (std::abs(test2) > std::abs(test1) && massChecker > network.massTol) {
                                              ^~~~~~~~
/usr/include/stdlib.h:129:6: note: candidate function
int      abs(int) __pure2;
         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:159:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:161:44: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
                                           ^
In file included from /Users/Dan/Desktop/Research/FERN/fernRefactor/fern/src/main.cpp:39:
/Users/Dan/Desktop/Research/FERN/fernRefactor/fern/src/DefaultStepper.h:146:11: error: use of undeclared identifier 'fmax'
                                dt *= fmax( network.massTol     / massChecker, downbumper);
                                      ^
/Users/Dan/Desktop/Research/FERN/fernRefactor/fern/src/DefaultStepper.h:148:31: error: use of undeclared identifier 'fmax'
                                dt *= (network.massTol / (fmax(massChecker, upbumper)));**
                                                          ^
5 errors generated.

**Comment by BenBrock** [comment]
Make sure CMAKE_CXX_COMPILER is set to gcc-4.8 or whatever GCC compiler
you have installed.  Right there it's using Apple's LLVM stuff.  I
recommend you install GCC 5.3.

You might be able to fix it by setting -std=c++11 or change std::abs()
to std::fabs(), but I'm not sure.  I don't know much about std::abs(),
but they added a templated version in C++11 that we might be utilizing
there.

Ben

**Comment by danshyles** [comment]
Alright, Ben fixed this. All I needed to was to set my compiler to CXX=g++-5 ! All good now. :)
